language: python
sudo: false
cache:
  directories:
    - eggs
    - .npm
addons:
  apt_packages:
  - graphviz
env:
  global:
    - secure: "TJYx9N1ZqFPTt5IBhc7GRQNEr5d7HlhRzXv8UnWCT1OSW4j1AHhXJ2Uql4tIUx0frwrSySCOMx+PFtg0vvf0iYOAR4jNl+/cgLV/6JgtnuGiKG3Pwyu7r3ED0I2v0ZV2jSVGAd0VW5/l4Wq7ZFRaPb6YQHKQ6HIhM+4CXaITT3Gg5+Q/ELCMTuxYqG0kFmRAuu+qsJYOFrbxvGuELhlRuYsSGKJj95YuJO2ImHLbbhwyERUPsVtZPk3om10TAT3o+nNqfy+CZNTmi7jusYcdOO/OJ8CDD/CM9bBnr65TQZix6ThTDT0wsGDYQiIgopWiu+reAkDAvI1zkOZcFHket7On1lC6eBATSTg1NZOV+aaSTJsyZzGH8qjGgOhsnIqTwrQ5/IphzzuORnpP2L1x0njYTssAM7F4xeCmlrLohzEsp2GLVacZE13kwZc1HLcldxM8deTtksoQxEZxFa6m4awOuBZqDTyAYUaf8BKv1YBGeNUxuUBe0e7o9AyS8cuOBfDaZ0/8I2hMgW2oXK6r+Gj8oZCaY1eY02b+E2LOZIiRiHxSjwMmi9TgySuQDWCjnv7Mqi3cWFiMshXNdPwASe0uRG1vskNwXJR9iBumvHPWcKUtb+LAGfSGAHfTnmWex3xcsDfLC6lgmxp/ZWWcUNJ1I38TIaoR0LLeU+k+DSg="
    - secure: "VU4CFUVXtaiDY+9+ic2RR7A5jzpPkRIw0D0txoLiAJPw6pjtAuifiNBF0q1f9WIEL7KX97ekJgskPN+3Z20AYpe9FHwR8JiMAxvHudI8ygjP8dwJ6Asr4MssvfToXzkdKRkV8fPnREgy9tNPrZTGp2X7oexr5D8rSKjwrVqtVDQJCKaHPIDgWwo877KLsn8pTJcGCJ76IT7xmXwRDkFnxOZgQPIJaiyXLhf28zO+GvgkXQu1dpvuhk+SeAMyIgpaRRvIEnUV4z4kGet/nfwzxI9H8zZoqyJemgMyVZeES2TKfjXKpCO+QqxgYsoteUDu41yKV4p/0UuuTsgD/yEm7Fe0T1aTu5nJAaS5cQjWjuCYUF3KmZKHcEnkU9ASn3AOEBNkK1zZrvu772Gnky+22kgcrrWqBbzw6FRkfYGHnuAQqg6NUtazrFJKxBEAZ5fefc4328xYV8N/RPhIU7x8diRmzSMctEdpyj6Ie7F1nYzE3LEqBCJugzhDzE+PhqYwG17KTJGnMOtNtc4ohX0GNK3bS1aeMWquRMozuUYq4XlBYqSyQnk7njbbbJ9kr4bm/RJhgX3ZgoWnkY3NxbwJIF2r4Px4IuMF0qgLq8G/H90tnSXSv3HU4oT/oXZt6IqmoDwzll9AaCiPO7/csqOJ8KrIYtTj6kXpU2zEHWcSaeA="
    - PATH="/usr/share/elasticsearch/bin:/usr/lib/postgresql/9.4/bin:$PATH"
matrix:
  include:
    - python: "3.4"
      env: BROWSER=Chrome
    - python: "3.4"
      env: BROWSER=
before_install:
  - whereis elasticsearch
  - postgres --version
  - initdb --version
  - elasticsearch -v
  - nvm install 5
  - node --version
install:
  - npm config set python /usr/bin/python2.7
  - python bootstrap.py -v 2.3.1 --setuptools-version 15.2
  - bin/buildout -c buildout-travis.cfg || (echo "Retrying buildout" && bin/buildout -c buildout-travis.cfg)
before_script:
  - >
    if test -n "$BROWSER"; then
      CONNECT_URL=https://saucelabs.com/downloads/sc-4.3.11-linux.tar.gz
      CONNECT_DOWNLOAD=sc.tar.gz
      SC_READYFILE=$HOME/sauce-connect-ready-$RANDOM
      SC_LOGFILE=$HOME/sauce-connect.log
      SC_PIDFILE=$HOME/sauce-connect.pid
      curl $CONNECT_URL > $CONNECT_DOWNLOAD
      mkdir sc
      tar -zxf $CONNECT_DOWNLOAD --strip 1 --directory sc
      sc/bin/sc --readyfile $SC_READYFILE \
        --logfile $SC_LOGFILE \
        --pidfile $SC_PIDFILE \
        --tunnel-identifier $TRAVIS_JOB_NUMBER \
        --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY > /dev/null &
      while test -f "$SC_PIDFILE" && test ! -f "$SC_READYFILE"; do 
        sleep 0.5
      done
    fi
script:
  - if test -z "$BROWSER"; then npm test; fi
  - if test -z "$BROWSER"; then bin/test -v -v --timeout=300 -m "not bdd"; fi
  - >
    if test -n "$BROWSER"; then
      test -s "$SC_PIDFILE" && bin/test -v -v --timeout=300 -m "bdd" --tb=short \
        --splinter-implicit-wait 10 \
        --splinter-webdriver remote \
        --splinter-remote-url "http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@localhost:4445/wd/hub" \
        --splinter-socket-timeout 300 \
        --browser-arg tunnel-identifier "$TRAVIS_JOB_NUMBER" \
        --browser-arg-int build  "$TRAVIS_BUILD_NUMBER" \
        --browser-arg-int idleTimeout 300 \
        --browser-arg name "$TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_COMMIT" \
        --browser-arg browser "$BROWSER"
    fi
after_script:
  - >
    if test -f "$SC_PIDFILE"; then
      # NOTE: Selenium Session ID/Sauce Connect Job ID is no longer stored in sauce-connect.log
      # SAUCE_JOB_ID=`grep -m 1 /session/ "$HOME/sauce-connect.log" | cut -d / -f 7`
      # SAUCE_PASSED=`((TRAVIS_TEST_RESULT == 0)) && echo true || echo false`
      # curl -H "Content-Type:text/json" -s -X PUT -d "{\"passed\": $SAUCE_PASSED}" \
      #   "http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@saucelabs.com/rest/v1/$SAUCE_USERNAME/jobs/$SAUCE_JOB_ID" > /dev/null
      echo "Sauce test page https://saucelabs.com/tests/$SAUCE_JOB_ID"
      # Wait for Sauce Connect to shut down its tunnel.
      echo "Closing Sauce Connect tunnel."
      SC_PID="$(cat $SC_PIDFILE)"
      kill $SC_PID
      wait $SC_PID
    fi
